version: '3.8'

services:

    nsqlookupd:
        image: nsqio/nsq
        command: /nsqlookupd
        ports:
            # Consumers need to suscribe to this port!
            - "4160:4160"
            - "4161:4161"

    # So if doing a final deploy change the command, command out ports and network modes.
    # When running in "network_mode: host" everytjhing is available via localhost.
    # This is needed because how nsqd and lookup interact. The lookup returns the docker internal IP.
    # As a result Client cannot connect.
    nsqd:
        image: nsqio/nsq
        command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
        # command: /nsqd --lookupd-tcp-address=127.0.0.1:4160
        depends_on:
            - nsqlookupd
        ports:
            # Messages need to be send to this port ?!
            - "4150:4150" 
            - "4151:4151"
        # network_mode: host
        # deploy:
        #     replicas: 1

    nsqadmin:
        image: nsqio/nsq
        command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
        # command: /nsqadmin --lookupd-http-address=127.0.0.1:4161
        depends_on:
            - nsqlookupd  
        ports:
            - "4171:4171"
        # network_mode: host

    gobackend:
        build: ./backend
        volumes:
            - ./backend:/usr/src/backend
        # restart_policy:
        #     condition: on-failure
        #     delay: 3s
        #     max_attempts: 2
        #     window: 120s
        
        # Unnessary because its overwritten by docker-compose.override.yml
        # ports: 
        #     - "8080:8080"
        depends_on:
            - postgresDB
            - redisCache
            - nsqd
            - jaegertracing
            - nats
            - grpcconsumer
        environment:
            - DATABASE_URL=postgres://postgres:postgres@postgresDB:5432
            - CACHE_URL=redisCache
            - NSQ_DEMON=nsqd
            - JAEGER_URL=jaegertracing:14268
            - TRACING_URL=tracingapp:8001
            - MY_NAME=test
            - NATS_URL=nats
            - GRPC_URL=grpcconsumer:7777

        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.gobackend.rule=Host(`randompage.local`)"
            - "traefik.http.routers.gobackend.entrypoints=web"

    # Simple Consumer
    nsqconsumer_links:
        build: ./nsqconsumer
        volumes:
            - ./nsqconsumer:/usr/src/nsqconsumer
        depends_on:
            - postgresDB
            - redisCache
            - nsqlookupd
            - nsqd
        environment:
            - NSQ_LOOKUP=nsqlookupd
            - NSQ_TOPIC=default
            - NSQ_CHAN=links
            - JAEGER_URL=jaegertracing:14268
        deploy:
            replicas: 1

    # Same as _links but different Channel
    nsqconsumer_rechts:
        build: ./nsqconsumer
        volumes:
            - ./nsqconsumer:/usr/src/nsqconsumer
        depends_on:
            - postgresDB
            - redisCache
            - nsqlookupd
            - nsqd
        environment:
            - NSQ_LOOKUP=nsqlookupd
            - NSQ_TOPIC=default
            - NSQ_CHAN=rechts
            - JAEGER_URL=jaegertracing:14268
        deploy:
            replicas: 1

    tracingapp:
        build: ./tracingApp
        depends_on:
            - gobackend
        volumes:
            - ./tracingApp:/usr/src/tracingApp
        environment:
            - JAEGER_URL=jaegertracing:14268
        ports:
            - "8001:8001"

    natsconsumer:
        build: ./natsconsumer
        depends_on:
            - nats
        environment:
            - NATS_URL=nats
        volumes:
          - ./natsconsumer:/usr/src/natsconsumer

    # Consumes the messages produced from the backend.    
    grpcconsumer:
        build: ./grpcconsumer
        environment:
            - JAEGER_URL=jaegertracing:14268
        ports:
            - "7777:7777"
        volumes:
          - ./grpcconsumer:/usr/src/grpcconsumer

    postgresDB:
        image: postgres:15.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        volumes:
            - ./db.sql:/docker-entrypoint-initdb.d/db.sql
            - db:/var/lib/postgresql/data
  
    postgres-exporter:
        image: quay.io/prometheuscommunity/postgres-exporter
        environment:
            - DATA_SOURCE_NAME=postgresql://postgres:postgres@postgresDB:5432/postgres?sslmode=disable
        ports:
            - "9187:9187"

    redisCache:
        image: redis:7-alpine
        restart: always
        ports:
            - '6379:6379'
        # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        volumes: 
            - cache:/data

    prometheus:
        image: prom/prometheus:latest
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus

        depends_on:
            - gobackend

    #TODO still needs manual connection to Prometheus
    grafana:
        image: grafana/grafana:latest
        # user: "472"
        depends_on:
            - prometheus
        ports:
        - 3000:3000
        volumes:
        - grafana_data:/var/lib/grafana
        - ./grafana.yml:/etc/grafana/provisioning/datasources/datasource.yml
        # env_file:
        # - ./grafana/config.monitoring


    # Dont know why but it works with the defaults and not with custom ConfigFile.
    loki:
        image: grafana/loki:2.7.0
        ports:
        - "3100:3100"
        depends_on:
            - promtail
        # command: "-config.file=/etc/loki/config.yaml -target=read"
        # volumes:
        # - ./loki-config.yaml:/etc/loki/config.yaml

    promtail:
        image: grafana/promtail:2.7.0
        volumes:
        - ./promtail-local-config.yaml:/etc/promtail/config.yaml:ro
        - /var/run/docker.sock:/var/run/docker.sock
        command: -config.file=/etc/promtail/config.yaml

    jaegertracing:
        image: jaegertracing/all-in-one:latest
        ports:
            - "5775:5775/udp"
            - "6831:6831/udp"
            - "6832:6832/udp"
            - 5778:5778
            - "16686:16686"
            - "14268:14268"
            - "9411:9411"
        environment:
            - COLLECTOR_ZIPKIN_HTTP_PORT=9411

    nats:
        image: nats:latest
        ports:
            - "4222:4222"
            - "8222:8222"

    traefik:
        image: "traefik:v2.9"
        command:
        #- "--log.level=DEBUG"
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.web.address=:80"
        - "--entrypoints.web2.address=:443"
        # - "--providers.file.directory=/etc/traefik/dynamic"
        ports:
        - "80:80"
        - "8088:8080"
        volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
    db:
        driver: local
    cache:
        driver: local
    prometheus_data:
        driver: local
    grafana_data:
        driver: local
