FROM alpine:latest

WORKDIR /usr/src/natsconsumer

COPY natsconsumer /usr/src/natsconsumer/natsconsumer

# EXPOSE 8080

# ENV DATABASE_URL="postgresql://postgres:postgres@db:5432"

CMD [ "./natsconsumer" ]
