FROM alpine:latest

WORKDIR /usr/src/grpcconsumer

COPY grpcconsumer /usr/src/grpcconsumer/grpcconsumer

EXPOSE 7777

# ENV DATABASE_URL="postgresql://postgres:postgres@db:5432"

CMD ["./grpcconsumer" ]

# CMD ["/usr/local/bin/shell.sh"]
